name: Task Template
description: Create a new task
title: "Task"
labels: ["task"]
projects: ["Equindar/2"]
body:
  - type: textarea
    id: task-description
    attributes:
      label: Description of the Task
      description: Provide a brief Description what has to be done
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Equindar/LunarEclipse/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true