name: Task Template
description: Erstelle eine neue Aufgabe
title: 'Aufgabe'
labels: ['task']
projects: ['Equindar/2']
body:
  - type: textarea
    id: task-description
    attributes:
      label: Beschreibung (Aufgabe)
      description: Erstelle eine kurze Beschreibung für die Aufgabe
    validations:
      required: true
  - type: markdown
    attributes:
      value: Durch das Einreichen des Issues akzeptierst du den folgenden [Code of Conduct](https://github.com/Equindar/LunarEclipse/blob/main/CODE_OF_CONDUCT.md)
