name: User Story Template
description: Erstelle eine neue UserStory
title: 'User-Story'
labels: ['userstory']
projects: ['Equindar/2']
assignees:
  - Equindar
body:
  - type: textarea
    id: user-story
    attributes:
      label: Beschreibung (UserStory)
      description: Als ein [Art des Benutzers], möchte ich [Aufgabe/Anliegen durchführen] damit ich [Ziel erreiche].
    validations:
      required: true
  - type: markdown
    attributes:
      value: Durch das Einreichen des Issues akzeptierst du den folgenden [Code of Conduct](https://github.com/Equindar/LunarEclipse/blob/main/CODE_OF_CONDUCT.md)
