name: Deploy API (Docker)

on:
  push:
    branches:
      - production
    tags:
      - "v*.*.*"

jobs:
  build-api:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./apps/api

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Login to GHCR with user: equindar
      - name: Log in to GitHub Container Registry
        run: |
          docker login --username equindar --password ${{ secrets.GH_PAT }} ghcr.io

      # Build Docker image
      - name: Build Docker image
        run: |
          VERSION=${{ github.ref_name }}
          IMAGE_NAME=${{ vars.APPS_API_IMAGE_NAME }}

          docker build \
            -f apps/api/Dockerfile \
            --build-arg NODE_ENV=production \
            -t ghcr.io/equindar/$IMAGE_NAME:$VERSION \
            -t $IMAGE_NAME:latest \
            .

      # Push Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/equindar/$IMAGE_NAME:$VERSION
          docker push ghcr.io/equindar/$IMAGE_NAME:latest
