name: Docker Image CI for GitHub ContainerRegistry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_publish:
    name: Build and Publish package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.devcontainer
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the image
        run: |
          docker login --username equindar --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/equindar/test-package:latest
          docker push ghcr.io/equindar/test-package:latest
